class EndPoints {
  factory EndPoints() {
    return _instance;
  }
  EndPoints._();
  static final EndPoints _instance = EndPoints._();
  static const String baseUrl = "https://back.welyra.com/api/v1/";
  static const String baseUrlImgs = "https://back.welyra.com/";
  static const String register = "register";
  static const String login = "login";
  static const String forgotPassword = "forgot-password";
  static const String checkLocation = "user/checkNewLocation";
  static const String verfiyOtpApi = "verfiyOtpApi";
  static const String resendOtpAgainApi = "resendOtpAgainApi";
  static const String resetPassword = "reset-password";
  static const String userProfile = "user";
  static const String editUserProfile = "user/updateUserProfile";
  static const String adresses = "user/addresses/all";
  static const String addNewAddress = "user/addresses/add";
  static const String deleteAddress = "user/addresses/unActive/";
  static const String selectNewAddress = "user/addresses/selected/";
  static const String updateLocation = "user/addresses/update/";
  static const String homeData = "home";
  static const String categories = "categories";
  static const String allrpoducts = "home/product/all";
  static const String featuredProducts = "featuredProducts";
  static const String favouriteShops = "favoriteVendors";
  static const String addToCart = "user/cart/addProduct";
  static const String productDetails = "home/product/show";
  static const String showCartDetails = "user/cart/showDetails";
  static const String cartCheckout = "user/cart/checkOut/";
  static const String popularVendors = "home/allNearestVendors";
  static const String homeCategory = "home/category/";
  static const String allNearestVendors = "/allNearestVendors";
  static const String addProductRate = "home/product/addRating";
  static const String homeVendor = "home/vendor/";
  static const String parentCategories = "/parentCategories";
  static const String modifyProduct = "user/cart/modifyProduct";
  static const String allCarts = "user/cart/all";
  static const String closedCart = "user/cart/closed";
  static const String allNotifications = "notifications";
  static const String homeParentcategory = "home/parentCategory/";
  static const String homeParentcategoryVendors = "vendors";
  static const String parentCategory = "/parentCategory/";
  static const String subLevel = "/subLevel/";
  static const String allProducts = "/allProducts";
  static const String likeProduct = "user/LikeProduct/store";
  static const String disLikeProduct = "user/LikeProduct/remove/";
  static const String allSubLevels = "/allSubLevels";
  static const String allLikedProduct = "user/LikeProduct/all";
  static const String createOrder = "user/order/Create";
  static const String payTabCallBack = "user/order/PayTab/Callback";
  static const String allOrders = "user/allOrders";
  static const String sendMessage = "Support/Chats/sendMessage";
  static const String getMessage = "Support/Chats/allMessages";
  static const String getALLOrdersNotRate = "user/allOrdersNotRate";
  static const String pointsRewards = "user/pointsRewards";
  static const String orderDetails = "user/order/show/";
  static const String scheduleOrderDetails = "user/scheduleOrder/show/";
  static const String cancelOrder = "user/order/cancel/";
  static const String cancelScheduleOrder = "user/scheduleOrder/cancel/";
  static const String updateOrder = "user/order/update";
  static const String logout = "logout";
  static const String deleteAcount = "deleteAcount";
  static const String checkDiscount = "user/order/checkDiscount";
  static const String notificationToken = "notifications/storeToken";
  static const String addNewCard = "user/paytabs/saveCard";
  static const String callbackCard = "user/paytabs/CallbackCard";
  static const String allReplacements = "user/orders/allReplacements";
  static const String chngeStatusReplacement =
      "user/orders/replacements/handleProduct";
  static const String getScheduledOrders = "user/allScheduleOrders";
  static const String rateOrder = "user/order/rateOrder";
  static const String searchHome = "home/search";
  static const String itemSearchDetails = "home/search/productWithVendors";
  ////////////////Blogs//////////////////
  static const String homeBlogs = "blogsToCategory/";
  static const String blogDetails = "blogs/";
  static const String addToFav = "blogs/";
  static const String searchBlog = "blogs/search";
  static const String sendComment = "blogs/sendComment";
  static const String allSavedBlogs = "blogs/allBlogsSaved";
}
